### ISSUE TITLE
Error Failed resolution of ImageAsset when use GlideImage("url") 

### ISSUE THREAD

**Issue by DavidIbrahim** [mvarnagiris/compose-glide-image#11]
When I am trying to use GlideImage fun like this ` GlideImage("https://randomuser.me/api/portraits/men/35.jpg", modifier = modifier)`
I get the following error:
```
 java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/ui/graphics/ImageAsset;
        at com.koduok.compose.glideimage.GlideImageKt$GlideImage$2.invoke$lambda-1(GlideImage.kt:147)
        at com.koduok.compose.glideimage.GlideImageKt$GlideImage$2.invoke(GlideImage.kt:86)
        at com.koduok.compose.glideimage.GlideImageKt$GlideImage$2.invoke(Unknown Source:13)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:155)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.ui.layout.LayoutKt$WithConstraints$1$1$placeables$1.invoke(Layout.kt:538)
        at androidx.compose.ui.layout.LayoutKt$WithConstraints$1$1$placeables$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1.invoke(SubcomposeLayout.kt:169)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:2906)
        at androidx.compose.runtime.Composer.composeInitial(Composer.kt:2046)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:566)
        at androidx.compose.runtime.Composer$CompositionReferenceImpl.composeInitial$runtime_release(Composer.kt:2459)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:109)
        at androidx.compose.ui.platform.WrapperKt.subcomposeInto(Wrapper.kt:127)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(SubcomposeLayout.kt:163)
        at androidx.compose.ui.layout.SubcomposeLayoutState$subcompose$2.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.pauseObservingReads(SnapshotStateObserver.kt:147)
        at androidx.compose.ui.node.OwnerSnapshotObserver.pauseSnapshotReadObservation$ui_release(OwnerSnapshotObserver.kt:52)
        at androidx.compose.ui.node.LayoutNode.ignoreModelReads$ui_release(LayoutNode.kt:1104)
        at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:161)
        at androidx.compose.ui.layout.SubcomposeLayoutState.subcompose(SubcomposeLayout.kt:155)
        at androidx.compose.ui.layout.LayoutKt$WithConstraints$1$1.invoke(Layout.kt:538)
        at androidx.compose.ui.layout.LayoutKt$WithConstraints$1$1.invoke(Unknown Source:10)
        at androidx.compose.ui.layout.SubcomposeLayoutState$createMeasureBlocks$1.measure-8A2P9vY(SubcomposeLayout.kt:199)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:43)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1212)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt:126)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Unknown Source:13)
2021-01-18 10:15:28.866 7656-7656/com.linguistic.linguistic E/AndroidRuntime:     at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:390)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:43)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.foundation.layout.SizeModifier.measure-za8Wrwc(Size.kt:711)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:35)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.foundation.layout.PaddingModifier.measure-za8Wrwc(Padding.kt:210)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:35)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1212)
        at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(RowColumnImpl.kt:88)
        at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasureBlocks$1.invoke(Unknown Source:13)
        at androidx.compose.ui.layout.LayoutKt$measureBlocksOf$1.measure-8A2P9vY(Layout.kt:144)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:43)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(Size.kt:645)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:35)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1212)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt:104)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Unknown Source:13)
        at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:390)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:43)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
2021-01-18 10:15:28.867 7656-7656/com.linguistic.linguistic E/AndroidRuntime:     at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1212)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Box.kt:126)
        at androidx.compose.foundation.layout.BoxKt$boxMeasureBlocks$1.invoke(Unknown Source:13)
        at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:390)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:43)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(Size.kt:645)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:35)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1212)
        at androidx.compose.material.SurfaceKt$SurfaceLayout$1.invoke(Surface.kt:145)
        at androidx.compose.material.SurfaceKt$SurfaceLayout$1.invoke(Unknown Source:13)
        at androidx.compose.ui.layout.LayoutKt$MeasuringIntrinsicsMeasureBlocks$1.measure-8A2P9vY(Layout.kt:390)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:43)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-za8Wrwc(GraphicsLayerModifier.kt:201)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:35)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-za8Wrwc(GraphicsLayerModifier.kt:201)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:35)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.foundation.layout.FillModifier.measure-za8Wrwc(Size.kt:645)
        at androidx.compose.ui.node.ModifiedLayoutNode.performMeasure-BRTryo0(ModifiedLayoutNode.kt:35)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0)
2021-01-18 10:15:28.867 7656-7656/com.linguistic.linguistic E/AndroidRuntime:     at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:131)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:65)
        at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1212)
        at androidx.compose.ui.layout.RootMeasureBlocks.measure-8A2P9vY(RootMeasureBlocks.kt:38)
        at androidx.compose.ui.node.InnerPlaceable.performMeasure-BRTryo0(InnerPlaceable.kt:43)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.DelegatingLayoutNodeWrapper.performMeasure-BRTryo0(DelegatingLayoutNodeWrapper.kt:107)
        at androidx.compose.ui.node.LayoutNodeWrapper.measure-BRTryo0(LayoutNodeWrapper.kt:151)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(OuterMeasurablePlaceable.kt:93)
        at androidx.compose.ui.node.OuterMeasurablePlaceable$remeasure$2.invoke(Unknown Source:0)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1710)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:126)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:92)
        at androidx.compose.ui.node.LayoutNode.remeasure-BRTryo0$ui_release(LayoutNode.kt:1219)
        at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-ivNzw_s(MeasureAndLayoutDelegate.kt:170)
        at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$doRemeasure-ivNzw_s(Unknown Source:0)
        at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:211)
        at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.kt:444)
        at android.view.View.measure(View.java:24824)
        at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.kt:204)
        at android.view.View.measure(View.java:24824)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6934)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24824)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6934)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
        at android.view.View.measure(View.java:24824)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6934)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24824)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6934)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
        at android.view.View.measure(View.java:24824)
2021-01-18 10:15:28.868 7656-7656/com.linguistic.linguistic E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6934)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24824)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6934)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24824)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6934)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:24824)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6934)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:806)
        at android.view.View.measure(View.java:24824)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3357)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2117)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2411)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2001)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8208)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1085)
        at android.view.Choreographer.doCallbacks(Choreographer.java:908)
        at android.view.Choreographer.doFrame(Choreographer.java:835)
        at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:1013)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:7826)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.ui.graphics.ImageAsset" on path: DexPathList[[zip file "/data/app/com.linguistic.linguistic-vt_FbsuqI3N3upM6qT_bhw==/base.apk"],nativeLibraryDirectories=[/data/app/com.linguistic.linguistic-vt_FbsuqI3N3upM6qT_bhw==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by arqlz** [comment]
Same
